### ISSUE TITLE
Mastered Job 1HR cooldowns not consistent between bars

### ISSUE THREAD

**Issue by BlackmoreKnight** [ThornyFFXI/tTimers#7]
I'm on a mastered WAR and using Mighty Strikes results in a cooldown bar that starts empty with a 45m duration, while using Brazen Rush results in a cooldown bar that starts 25% full and is a 1 hour bar. Both convey the correct information but the display is currently inconsistent. I don't know if this is the same for other jobs as I only tested it on WAR (it might also be the other way around as to which SP ability displays which way, my memory isn't 100% clear).

**Comment by ThornyFFXI** [comment]
The client doesn't receive max recast data, tTimers sets the duration used for calculating bar progress based on the longest recast it's seen for a particular ability.  Hardcoding them is also likely to be a bad idea, given many users are on private servers and still have 2-hour recasts for their SP abilities.  With that in mind, I think the best solution is probably to remove the 'longest recast seen' and use the recast present anytime it goes from zero to non-zero, which would represent the most recent usage.

This won't fully fix it either, though.  There will be the edge case where you use the ability on an unmastered job then change to a mastered job and the timer is still counting based on 1 hour.  I do not think it's preferable to change it to 45 minutes in this case, since the timer could still exceed 45 minutes.

Either way, implemented this change in 0.07.
